Repository AY2324S1-CS2103T-W11-2/tp, pull requests merged in 2023-10, with the labels that each got.

#14 add AboutUs and PPP for nicolengk
  docs/AboutUs.md
  docs/images/nicolengk.png
  docs/team/nicolengk.md
Labels: type.Task, priority.High

#11 update ug for listprop and exit
  docs/UserGuide.md
Labels: type.Task, priority.High

#10 update sitewide settings for PropertyMatch
  docs/UserGuide.md
  docs/_config.yml
  docs/_sass/minima/_base.scss
  docs/index.md
Labels: type.Task, priority.High

#32 add github actions build status
  README.md
Labels: type.Task, priority.High

#37 add targetUser and valueProposition
  docs/DeveloperGuide.md
Labels: type.Task, priority.High

#36 add addprop to userguide
  docs/UserGuide.md
Labels: type.Task, priority.High

#31 add about us and PPP for chrainx
  docs/AboutUs.md
  docs/images/chrainx.png
  docs/team/chrainx.md
Labels: type.Task, priority.High

#34 add all nfr
  docs/DeveloperGuide.md
Labels: type.Task, priority.High

#41 Add use cases for dg
  docs/DeveloperGuide.md
Labels: type.Task, priority.High

#42 update glossary in DG
  docs/DeveloperGuide.md
Labels: type.Task, priority.High

#44 remove traces of ab3
  docs/UserGuide.md
Labels: type.Task, priority.High

#47 add qn
  docs/UserGuide.md
Labels: type.Task, priority.Medium

#48 Add question for FAQ
  docs/UserGuide.md
Labels: type.Task, priority.Medium

#50 Add question for FAQ
  docs/UserGuide.md
Labels: type.Task, priority.Medium

#52 Add question to uninstall in FAQ
  docs/UserGuide.md
Labels: priority.High

#58 Feat/proper exit command
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/ui/MainWindow.java
Labels: type.Task, priority.High

#61 remove address book traces
  src/main/java/seedu/address/MainApp.java
  src/main/resources/view/MainWindow.fxml
Labels: type.Task, priority.Medium

#59 Create Add Property
  build.gradle
  config/checkstyle/checkstyle.xml
  docs/UserGuide.md
  docs/team/johndoe.md
  docs/tutorials/TracingCode.md
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddPropertyCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandPropertyParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/PropertyBook.java
  src/main/java/seedu/address/model/ReadOnlyPropertyBook.java
  src/main/java/seedu/address/model/ReadOnlyUserPrefs.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/property/Price.java
  src/main/java/seedu/address/model/property/PropAddress.java
  src/main/java/seedu/address/model/property/PropName.java
  src/main/java/seedu/address/model/property/PropNameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/property/PropPhone.java
  src/main/java/seedu/address/model/property/Property.java
  src/main/java/seedu/address/model/property/UniquePropertyList.java
  src/main/java/seedu/address/model/property/exceptions/DuplicatePropertyException.java
  src/main/java/seedu/address/model/property/exceptions/PropertyNotFoundException.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedProperty.java
  src/main/java/seedu/address/storage/JsonPropertyBookStorage.java
  src/main/java/seedu/address/storage/JsonSerializablePropertyBook.java
  src/main/java/seedu/address/storage/PropertyBookStorage.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PropertyCard.java
  src/main/java/seedu/address/ui/PropertyListPanel.java
  src/main/java/seedu/address/ui/PropertyStatusBarFooter.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PropertyListCard.fxml
  src/main/resources/view/PropertyListPanel.fxml
  src/main/resources/view/PropertyStatusBarFooter.fxml
  src/test/java/seedu/address/logic/LogicManagerTest.java
Labels: type.Task, priority.High

#62 Fix Add Prop Command Word
  src/main/java/seedu/address/logic/commands/AddPropertyCommand.java
Labels: type.Task, priority.High

#64 Fix unit testing for add customer command
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCustomerCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCustomerCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/customer/BudgetTest.java
  src/test/java/seedu/address/storage/JsonUserPrefsStorageTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
Labels: type.Task, priority.High

#66 Feat/list prop
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/commands/ListPropertyCommand.java
  src/main/java/seedu/address/logic/parser/AddPropertyCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/customer/Budget.java
  src/main/java/seedu/address/model/property/Price.java
  src/main/java/seedu/address/ui/CustomerCard.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PropertyCard.java
  src/main/resources/view/CustomerListPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PropertyListCard.fxml
  src/main/resources/view/PropertyListPanel.fxml
Labels: type.Story, priority.High

#69 Add listcust feature
  src/main/java/seedu/address/logic/commands/ListCustomerCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: type.Story, priority.High

#71 remove debug statements
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/CustomerCard.java
Labels: type.Task, priority.Medium, severity.Low

#86 Add tests for listcust feature
  src/test/java/seedu/address/logic/commands/ListCustomerCommandTest.java
Labels: type.Enhancement, priority.High

#93 Add editprop command
  src/main/java/seedu/address/logic/commands/EditPropertyCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/EditPropertyCommandParser.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/test/java/seedu/address/logic/commands/AddCustomerCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddPropertyCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandPropertyTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCustomerCommandTest.java
  src/test/java/seedu/address/logic/commands/DeletePropertyCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPropertyCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCustomerCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditPropertyCommandParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/testutil/EditPropertyDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PropertyUtil.java
Labels: type.Task, priority.High

#94 Fix cicd pipeline errors
  build.gradle
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCustomerCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddPropertyCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/CommandPropertyTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCustomerCommandTest.java
  src/test/java/seedu/address/logic/commands/DeletePropertyCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPropertyCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCustomerCommandTest.java
  src/test/java/seedu/address/logic/commands/ListPropertyCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/model/property/PropNameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/property/PropNameTest.java
  src/test/java/seedu/address/model/property/PropertyTest.java
  src/test/java/seedu/address/testutil/TypicalProperties.java
Labels: type.Enhancement, priority.Medium

#95 Trial jar release
  build.gradle
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/java/seedu/address/testutil/TypicalProperties.java
Labels: type.Bug, priority.High, severity.High

#98 Add dg for exit and editcust
  docs/DeveloperGuide.md
  docs/diagrams/EditCustomerSequenceDiagram.puml
  docs/images/EditCustomerSequenceDiagram.png
Labels: type.Task, priority.High

#101 Update docs
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/FindCustomerSequenceDiagram.puml
  docs/images/FindCustomerSequenceDiagram.png
Labels: type.Task, priority.High

#102 Add filter customers command
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/FilterCustomerSequenceDiagram.puml
  docs/images/FilterCustomerSequenceDiagram.png
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/commands/AddCustomerCommand.java
  src/main/java/seedu/address/logic/commands/FilterCustomerCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/FilterCustomerCommandParser.java
  src/main/java/seedu/address/model/customer/Budget.java
  src/main/java/seedu/address/model/customer/BudgetAndTagsInRangePredicate.java
  src/test/java/seedu/address/logic/commands/FilterCustomerCommandTest.java
  src/test/java/seedu/address/logic/parser/FilterCustomerCommandParserTest.java
  src/test/java/seedu/address/model/customer/BudgetAndTagsInRangePredicateTest.java
  src/test/java/seedu/address/model/customer/BudgetTest.java
Labels: type.Task, priority.High

#99 Update dg
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/MatchCustomerSequenceDiagram.puml
  docs/images/MatchCustomerSequenceDiagram.png
Labels: type.Story, priority.High

#106 update ug and dg
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/DeleteCustomerSequenceDiagram.puml
  docs/diagrams/DeletePropertySequenceDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/EditPropertySequenceDiagram.puml
  docs/images/DeleteCustomerSequenceDiagram.png
  docs/images/DeletePropertySequenceDiagram.png
  docs/images/DeleteSequenceDiagram.png
  docs/images/EditPropertySequenceDiagram.png
Labels: type.Task, priority.High

#107 Add predicate for Price and Tags for Filtering Properties
  src/main/java/seedu/address/model/property/Price.java
  src/main/java/seedu/address/model/property/PriceAndTagsInRangePredicate.java
  src/test/java/seedu/address/model/property/PriceAndTagsInRangePredicateTest.java
  src/test/java/seedu/address/model/property/PriceTest.java
Labels: type.Enhancement, priority.Medium

#110 Add edit customer feature
  src/main/java/seedu/address/logic/commands/EditCustomerCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/EditCustomerCommandParser.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCustomerCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCustomerDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditCustomerCommandParserTest.java
  src/test/java/seedu/address/testutil/CustomerUtil.java
  src/test/java/seedu/address/testutil/EditCustomerDescriptorBuilder.java
Labels: type.Story, priority.High

#112 Add findcust feature
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/commands/FindCustomerCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/FindCustomerCommandParser.java
  src/main/java/seedu/address/model/customer/NameContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/FindCustomerCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindCustomerCommandParserTest.java
Labels: type.Story, priority.High

#108 add Match feature
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/MatchCustomerCommand.java
  src/main/java/seedu/address/logic/commands/MatchPropertyCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/MatchCustomerCommandParser.java
  src/main/java/seedu/address/logic/parser/MatchPropertyCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/customer/Budget.java
  src/main/java/seedu/address/model/customer/SameCustomerPredicate.java
  src/main/java/seedu/address/model/property/Price.java
  src/main/java/seedu/address/model/property/Property.java
  src/main/java/seedu/address/model/property/SamePropertyPredicate.java
  src/main/java/seedu/address/storage/JsonAdaptedProperty.java
  src/main/java/seedu/address/ui/PropertyCard.java
  src/test/java/seedu/address/logic/commands/AddCustomerCommandTest.java
  src/test/java/seedu/address/logic/commands/AddPropertyCommandTest.java
  src/test/java/seedu/address/logic/commands/MatchCustomerCommandTest.java
  src/test/java/seedu/address/logic/parser/MatchCustomerCommandParserTest.java
  src/test/java/seedu/address/logic/parser/MatchPropertyCommandParserTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPropertyTest.java
Labels: type.Task, priority.High

#114 Add filter properties command
  src/main/java/seedu/address/logic/commands/FilterPropertyCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/FilterCustomerCommandParser.java
  src/main/java/seedu/address/logic/parser/FilterPropertyCommandParser.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/FilterPropertyCommandTest.java
  src/test/java/seedu/address/logic/commands/FilterPropertyDescriptorTest.java
  src/test/java/seedu/address/logic/parser/FilterPropertyCommandParserTest.java
  src/test/java/seedu/address/testutil/EditPropertyDescriptorBuilder.java
  src/test/java/seedu/address/testutil/FilterPropertyDescriptorBuilder.java
  src/test/java/seedu/address/testutil/TypicalProperties.java
Labels: type.Task, priority.High

#113 Add findprop feature
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/FindPropertyCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/FindPropertyCommandParser.java
  src/main/java/seedu/address/model/property/PropNameContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/FindPropertyCommandTest.java
  src/test/java/seedu/address/testutil/TypicalProperties.java
Labels: type.Story, priority.High

#117 Add FilterCustomerDescriptor
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/FilterCustomerSequenceDiagram.puml
  docs/images/FilterCustomerSequenceDiagram.png
  src/main/java/seedu/address/logic/commands/FilterCustomerCommand.java
  src/main/java/seedu/address/logic/commands/FilterPropertyCommand.java
  src/main/java/seedu/address/logic/parser/FilterCustomerCommandParser.java
  src/main/resources/view/PropertyListCard.fxml
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/FilterCustomerCommandTest.java
  src/test/java/seedu/address/logic/commands/FilterCustomerDescriptorTest.java
  src/test/java/seedu/address/testutil/FilterCustomerDescriptorBuilder.java
  src/test/java/seedu/address/testutil/FilterPropertyDescriptorBuilder.java
Labels: type.Enhancement, priority.Medium
