Repository AY2324S1-CS2103T-W11-2/tp, pull requests merged in 2023-11, with the labels that each got.

#120 Add clear command
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/resources/view/PropertyListCard.fxml
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
Labels: type.Story, priority.High

#115 Update landing page
  docs/images/Ui.png
Labels: type.Task, priority.High

#122 Add match ug
  docs/UserGuide.md
Labels: type.Story, priority.High

#164 Change to arrch64 to mac
  build.gradle
Labels: priority.High

#165 Format UG
  docs/UserGuide.md
Labels: type.Bug, severity.Low

#167 Chore/friendly ug 1.4
  docs/UserGuide.md
  docs/images/Logo.png
  docs/images/user-guide/HelpWindow.png
  docs/images/user-guide/UserInterface.png
Labels: type.Bug, priority.High, severity.Medium

#169 Add exit message
  docs/UserGuide.md
  src/main/java/seedu/address/ui/MainWindow.java
Labels: type.Bug, priority.High, severity.Low

#168 Fix table of contents in UserGuide.md
  docs/UserGuide.md
Labels: type.Bug, priority.High, severity.Medium

#173 Update findcust description
  docs/UserGuide.md
Labels: type.Bug, priority.Medium

#175 Update phone number parameter
  docs/UserGuide.md
Labels: type.Bug, priority.Medium

#176 Update editprop description
  docs/UserGuide.md
Labels: type.Bug, priority.Medium

#177 Chore/ppp draft
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/jianrong7.md
Labels: type.Task, priority.High

#181 Handle bugs for filtering without characteristics
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/model/customer/BudgetAndTagsInRangePredicate.java
  src/main/java/seedu/address/model/property/PriceAndTagsInRangePredicate.java
  src/test/java/seedu/address/model/customer/BudgetAndTagsInRangePredicateTest.java
  src/test/java/seedu/address/model/property/PriceAndTagsInRangePredicateTest.java
Labels: type.Bug, priority.High

#178 Update ppp
  docs/team/nicolengk.md
Labels: type.Task, priority.High

#180 Fix UG bugs
  docs/UserGuide.md
Labels: type.Bug, severity.Low

#183 Update PPP
  docs/team/ferdihs.md
Labels: type.Task, priority.High

#171 Fix match feature
  src/main/java/seedu/address/model/customer/BudgetAndOneTagsPredicate.java
  src/main/java/seedu/address/model/property/PriceAndOneTagsPredicate.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/test/java/seedu/address/logic/commands/MatchPropertyCommandTest.java
  src/test/java/seedu/address/logic/parser/MatchPropertyCommandParserTest.java
  src/test/java/seedu/address/model/customer/BudgetAndOneTagsPredicateTest.java
  src/test/java/seedu/address/model/property/PriceAndOneTagsPredicateTest.java
Labels: type.Task, priority.High

#187 Fix/invalid budget price
  src/main/java/seedu/address/model/customer/Budget.java
  src/main/java/seedu/address/model/property/Price.java
  src/main/resources/view/CustomerListPanel.fxml
  src/main/resources/view/PropertyListPanel.fxml
  src/test/java/seedu/address/model/customer/BudgetTest.java
  src/test/java/seedu/address/model/property/PriceTest.java
Labels: type.Bug, priority.High, severity.High

#188 Fix/invalid phone
  src/main/java/seedu/address/model/customer/Phone.java
  src/main/java/seedu/address/model/property/PropPhone.java
  src/test/data/JsonSerializableAddressBookTest/typicalCustomersAddressBook.json
  src/test/java/seedu/address/logic/commands/CommandPropertyTestUtil.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/customer/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/customer/PhoneTest.java
  src/test/java/seedu/address/model/property/PropNameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/property/PropPhoneTest.java
  src/test/java/seedu/address/testutil/TypicalCustomers.java
  src/test/java/seedu/address/testutil/TypicalProperties.java
Labels: type.Bug, priority.High, severity.High

#189 improve ug
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/startUi.png
  docs/images/user-guide/CommandBox.png
  docs/images/user-guide/HelpWindow.png
  docs/images/user-guide/Ui.png
  docs/images/user-guide/addcustUi.png
  docs/images/user-guide/delcustUi.png
  docs/images/user-guide/editcustUi.png
  docs/images/user-guide/filtercustUi.png
  docs/images/user-guide/findcustUi.png
Labels: type.Task, priority.Medium

#186 Update dg
  docs/DeveloperGuide.md
  docs/team/jianrong7.md
  docs/team/nicolengk.md
Labels: type.Task, priority.High

#192 Update budget parameter test
  src/main/java/seedu/address/model/customer/Budget.java
Labels: type.Bug, priority.Medium

#193 Fix/add handle dupe
  docs/UserGuide.md
  src/main/java/seedu/address/model/customer/Customer.java
  src/main/java/seedu/address/model/property/PropPhone.java
  src/main/java/seedu/address/model/property/Property.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/data/JsonSerializableAddressBookTest/duplicateCustomerByEmailAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicateCustomerByNameAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicateCustomerByPhoneAddressBook.json
  src/test/data/JsonSerializablePropertyBookTest/duplicatePropertyByAddressPropertyBook.json
  src/test/data/JsonSerializablePropertyBookTest/duplicatePropertyByNamePropertyBook.json
  src/test/data/JsonSerializablePropertyBookTest/duplicatePropertyByPhonePropertyBook.json
  src/test/data/JsonSerializablePropertyBookTest/invalidPropertyPropertyBook.json
  src/test/data/JsonSerializablePropertyBookTest/typicalPropertiesPropertyBook.json
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/model/customer/CustomerTest.java
  src/test/java/seedu/address/model/property/PropertyTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
  src/test/java/seedu/address/storage/JsonSerializablePropertyBookTest.java
Labels: type.Bug, priority.High, severity.High

#194 Update dg
  docs/DeveloperGuide.md
Labels: type.Bug, priority.Medium

#195 Update dg
  docs/DeveloperGuide.md
Labels: type.Bug, priority.Medium

#197 Fix/sample data util
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/EditCustomerCommand.java
  src/main/java/seedu/address/logic/commands/EditPropertyCommand.java
  src/main/java/seedu/address/model/customer/Budget.java
  src/main/java/seedu/address/model/customer/Customer.java
  src/main/java/seedu/address/model/property/Price.java
  src/main/java/seedu/address/model/property/Property.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/data/JsonSerializableAddressBookTest/duplicateCustomerByEmailAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicateCustomerByNameAddressBook.json
  src/test/data/JsonSerializablePropertyBookTest/duplicatePropertyByNamePropertyBook.json
  src/test/data/JsonSerializablePropertyBookTest/duplicatePropertyByPhonePropertyBook.json
  src/test/java/seedu/address/model/customer/BudgetTest.java
  src/test/java/seedu/address/model/customer/CustomerTest.java
  src/test/java/seedu/address/model/property/PriceTest.java
  src/test/java/seedu/address/model/property/PropertyTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
  src/test/java/seedu/address/storage/JsonSerializablePropertyBookTest.java
Labels: type.Bug, priority.High, severity.High

#199 Add title to Table of Contents in DeveloperGuide.md
  docs/DeveloperGuide.md
Labels: type.Bug, priority.High, severity.VeryLow

#198 Fix error msg
  src/main/java/seedu/address/logic/commands/EditCustomerCommand.java
  src/main/java/seedu/address/logic/commands/EditPropertyCommand.java
Labels: type.Bug, priority.High, severity.Low

#200 Minor fixes to UG from internal testing
  docs/UserGuide.md
Labels: type.Bug, priority.High, severity.High

#204 Fix PPP
  docs/team/jianrong7.md
Labels: type.Bug, priority.High

#203 Fix/add integration tests
  src/main/java/seedu/address/logic/commands/AddCustomerCommand.java
  src/main/java/seedu/address/logic/commands/AddPropertyCommand.java
  src/main/java/seedu/address/model/customer/Address.java
  src/main/java/seedu/address/model/property/PropAddress.java
  src/main/java/seedu/address/model/property/PropName.java
  src/main/java/seedu/address/model/property/PropPhone.java
  src/main/java/seedu/address/model/property/exceptions/DuplicatePropertyException.java
  src/test/java/seedu/address/logic/parser/FindPropertyCommandParserTest.java
  src/test/java/seedu/address/model/customer/AddressTest.java
  src/test/java/seedu/address/model/customer/NameTest.java
  src/test/java/seedu/address/model/customer/PhoneTest.java
  src/test/java/seedu/address/model/property/PropAddressTest.java
  src/test/java/seedu/address/model/property/PropNameTest.java
  src/test/java/seedu/address/model/property/UniquePropertyListTest.java
Labels: type.Bug, priority.Medium, severity.Medium

#201 add my personal contribution
  docs/team/chrainx.md
Labels: priority.High

#206 update ug
  docs/UserGuide.md
Labels: type.Task, priority.High

#205 Code reuse declaration
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/chrainx.md
  docs/team/jianrong7.md
Labels: type.Bug, priority.High, severity.Low

#207 Fix ppp
  docs/team/nicolengk.md
Labels: type.Task, priority.High

#221 Update name parameter constraints phrasing in ug
  docs/UserGuide.md
Labels: type.Bug, priority.Medium

#222 Update note for duplicate tags/characteristics
  docs/UserGuide.md
Labels: type.Bug, priority.Medium

#223 Add note that all INDEX params can start with 0
  docs/UserGuide.md
Labels: type.Bug, priority.High

#224 Update address param note for additional spaces
  docs/UserGuide.md
Labels: type.Bug, priority.High

#225 Update match feature description
  docs/UserGuide.md
Labels: type.Bug, priority.High

#226 Remove tip box at match feature description
  docs/UserGuide.md
Labels: type.Bug, priority.High

#227 Add warning for features with index parameter to use list after
  docs/UserGuide.md
Labels: type.Bug, priority.High

#228 Add activity diagram for delcust command
  docs/DeveloperGuide.md
  docs/diagrams/DeleteCustomerActivityDiagram.puml
  docs/images/DeleteCustomerActivityDiagram.png
Labels: type.Bug, priority.High

#230 Fix/no slash
  docs/UserGuide.md
  src/main/java/seedu/address/model/property/PropAddress.java
  src/main/java/seedu/address/model/property/PropName.java
  src/test/java/seedu/address/model/property/PropAddressTest.java
  src/test/java/seedu/address/model/property/PropNameTest.java
Labels: type.Bug, priority.High, severity.High

#232 Update error messages
  src/main/java/seedu/address/model/property/PropAddress.java
  src/main/java/seedu/address/model/property/PropName.java
Labels: type.Bug, priority.High, severity.High

#229 Chore/dg
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/AddCustomerActivityDiagram.puml
  docs/diagrams/AddPropertyActivityDiagram.puml
  docs/diagrams/CustomerObjectDiagram.puml
  docs/diagrams/EditCustomerSequenceDiagram.puml
  docs/diagrams/EditPropertySequenceDiagram.puml
  docs/diagrams/PropertyObjectDiagram.puml
  docs/images/AddCustomerActivityDiagram.png
  docs/images/AddPropertyActivityDiagram.png
  docs/images/CustomerObjectDiagram.png
  docs/images/DeleteSequenceDiagram.png
  docs/images/EditCustomerSequenceDiagram.png
  docs/images/EditPropertySequenceDiagram.png
  docs/images/PropertyObjectDiagram.png
Labels: type.Bug, priority.High, severity.High

#231 Remove Address in Customer since it is not used
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/customer/Address.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/customer/AddressTest.java
Labels: type.Enhancement, priority.Medium

#235 Fix/docs
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Bug, priority.High, severity.Medium

#237 Fix slashes and tests
  src/main/java/seedu/address/model/property/PropAddress.java
  src/main/java/seedu/address/model/property/PropName.java
  src/test/java/seedu/address/model/property/PropAddressTest.java
  src/test/java/seedu/address/model/property/PropNameTest.java
Labels: type.Bug, priority.High, severity.High
